### ISSUE TITLE
Some questions about OWT Client branchs & WebRTC branchs & OWT Server branchs

### ISSUE THREAD

**Issue by zzw315** [open-webrtc-toolkit/owt-client-native#501]
What's the difference between OWT Client 5.0 branch and other branches. 
Can OWT branch be combined with webrtc branch at will? 
Including the matching between OWT client and OWT server? 
What are the restrictions? 
Where can I see this information?

Thanks

**Comment by taste1981** [comment]
owt-client-native branch with name x.y.z is the release branch, and it is supposed to work only with owt-server branch or release version m.n.p where x<=m. 

Generally, if owt-server release version or branch version is 5.0.x,   owt-client-native branch is 4.3.x or 5.0.x, it should work;  otherwise, if owt-client-native branch is 5.0.x and owt-server version is 4.3.x, it will not work.

for WebRTC branch (owt-deps-webrtc), the actual version used by owt-client-native is specified by the DEPS file of owt-client-native, and may change commit by commit. You need to check  top-level DEPS file of owt-client-native to see which commit of owt-deps-webrtc is actually used.

**Comment by taste1981** [comment]
If no further question, I'm closing it.
